### ISSUE TITLE
PICKAXE_OF_CONTAINMENT & charges from CMI incompatibillity - duplication

### ISSUE THREAD

**Issue by Volgeop** [Slimefun/Slimefun4#2507]
## :round_pushpin: Description (REQUIRED)

Hi, when players are using PICKAXE_OF_CONTAINMENT to mine spawners and charge for mining spawners is active in CMI, then when players don't have charges to mine spawners (so they can't mine them, normally when they'll try to mine them without pickaxe then spawner isn't dropped, you can see video, but when they'll try do it via pickaxe of contaimnent, then it duplicates...)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Enable charges in config of CMI:
```
  Charges:
    # When enabled players will be assigned to particular spawner charges group who have cmi.spawners.charge.[groupName] permission node
    # Players will be limited to how many spawners they can mine
    # StartingCharge will determine how many charges they will have on first time joining group
    # MaxCharge will limit to how many charges you can have at one time
    # Cooldown determines how often new charge will be given
    # Bonus is optional and it will determine by how many seconds to lower cooldown for next charge when placing spawner
    # Option to bypass limitations with cmi.spawners.charge.bypass
    Use: true
    # If set to true when player runs out of spawner charges spawner will be destroyed without droping it
    BreakWithoutCharge: false
    List:
      Default:
        Use: true
        StartingCharge: 2
        MaxCharge: 2
        Cooldown: 43200
        Bonus: 3600
```
2. Set your charges to 0 - /charges <player> set 0
3. Mine spawner with PICKAXE_OF_CONTAINMENT, then it drops but spawner isn't broken, and it could be infinite source of spawners.....

## :bulb: Expected behavior (REQUIRED)

The spawner shouldn't be mined (dropped), or atleast it should be destroyed, one of these. But rather I be when it will respect CMI charges and won't drop, when player doesn't have any charges.

## :bulb: Videos
With and without charge - https://streamable.com/809hy3 (first I had 1 charge, then there were 0 of them for me and it duplicated)

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: 729
 - CS-CoreLib Version: 91
-  CMI version: 8.7.9.3

Reported to CMI Github too https://github.com/Zrips/CMI/issues/4474
