### ISSUE TITLE
Better NBT handling for spawners (CMI compatibility)

### ISSUE THREAD

**Issue by bobhenl** [Slimefun/Slimefun4#2583]
## :round_pushpin: Description (REQUIRED)

Hi, as reported here https://github.com/Zrips/CMI/issues/4605 on CMI issue tracker, there was problem when I had enabled place section in their config and then wanted to place specific type of Reinforced spawner, it didn't work.

But CMI isn't needed probably, as Zrips mentioned there, this is how REINFORCED SPAWNER nbt look:
![image](https://user-images.githubusercontent.com/18662086/100662239-eb20d900-3354-11eb-8012-ab050961baad.png)
And this is, how it should look, there's missing some important tags.
![image](https://user-images.githubusercontent.com/18662086/100662279-f70c9b00-3354-11eb-83b6-b9baaae733da.png)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. You don't need to use CMI? just look at nbt tags and try to fix.

IF you decide to reproduce with CMI, then:
1. Set 
```
  Place:
    # Enable or disable spawner handler for spawner place
    # If enabled player will place spawner depending from what it is by its type
    # If disabled then spawner will be placed in normal way and it will allow other plugins to handle its placement
    Enabled: true
    # If set to true, player will need to have appropriate permission node to place spawner by its type
    RequiresPermission: true
    # RequiresPermission should be set to true for this to work. If set to true, player will need to have particular permission node to place particular spawner.
    # In example: player should have cmi.placespawner.pig to place pig spawner, or cmi.placespawner.zombie to place zombie spawner
```
and then try to place some reinforced spawner... you will see it's pig always, even when you place spider spawner.

## :bulb: Expected behavior (REQUIRED)

Spider spawner should be placed as spider spawner, not the pig one. Better NBT mentioned in nbt tags.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.4
 - Slimefun Version: 757
 - CS-CoreLib Version: 91
CMI: 8.7.11.1
